data:
    path_main: '/home/igkinis/projects/datasets/subset_RAVDESS'
    outpath: '/home/igkinis/projects/datasets/subset_RAVDESS_mels'
    labels_metadata: { 1: 'neutral', 2: 'calm', 3: 'happy', 4: 'sad', 5: 'angry', 6: 'fearful',
                       7: 'disgust', 8: 'surprised' }
    save2disk: False
# xgb
#model:
#    max_depth: 10
#    min_child_weight: 1
#    n_estimators: 200
#    learning_rate: 0.05
#    use_label_encoder: False
# lgb
model:
    max_depth: 50
    learning_rate : 0.1
    num_leaves: 900
    n_estimators: 300
# RF
#model:
#    random_state: 42
#    n_jobs: 4
#    class_weight: "balanced"
#    n_estimators: 250
#    bootstrap: True
train:
    normalize: True
    test_size: 0.1
    split: True
    encoder: 'LabelEncoder'
    classifier: lgb
    feature_type: log_mel
    pooling: True
    grid_search: True
    folds: 5

param_grid: {"max_depth": [10,30,50],
              "min_child_weight" : [1,3,6],
              "n_estimators": [200],
              "learning_rate": [0.05, 0.1,0.16],}
grid_dict:
    n_jobs: 4
    refit: True
    scoring: "balanced_accuracy"
kf_dict:
    n_splits: 3
    random_state: 42
    shuffle: True